import { IntentIcon } from "@/lib/living-paris-intent/icons";
import type { LivingParisIntent } from "@/lib/living-paris-intent/types";
import type { DemoBundle } from "./types";

const CAFE_GRAD = "linear-gradient(135deg,#e0b48c,#c68b59)";
const PARK_GRAD = "linear-gradient(135deg,#a8cba0,#6b9a76)";
const VIEW_GRAD = "linear-gradient(135deg,#a8c4dc,#7ba0c0)";
const REST_GRAD = "linear-gradient(135deg,#e09475,#c4593a)";
const SHOP_GRAD = "linear-gradient(135deg,#c9bda9,#a3947d)";
const GALLERY_GRAD = "linear-gradient(135deg,#b9aef0,#9b8cff)";

export const DEMO_BUNDLES: Record<DemoBundle["id"], DemoBundle> = {
  "date-night-40": {
    id: "date-night-40",
    label: "Date Night · €40",
    emoji: "🌹",
    sceneId: "golden-hour",
    headerPill: "Paris · Été · Golden hour",
    accentColor: "#e879a9",
    glowColor: "rgba(232, 121, 169, 0.45)",
    mapMood: "romantic",
    title: "Date Night",
    subtitle: "Soft light, quiet corners — under €40",
    reply:
      "I found a low-key romantic loop — rooftop view, a tiny wine bar, and a slow walk while the light falls.",
    distance: "1.1 km",
    duration: "95 min",
    routePath: "M 72 210 C 110 195, 130 175, 165 168 S 220 145, 268 128 S 310 118, 338 108",
    markers: [
      {
        id: "rooftop",
        x: 34,
        y: 38,
        label: "Rooftop",
        sublabel: "le soleil tombe",
        highlighted: true,
        stopNumber: 1,
      },
      {
        id: "wine",
        x: 58,
        y: 52,
        label: "Le Verre",
        sublabel: "verre de vin",
        highlighted: true,
        stopNumber: 2,
      },
      {
        id: "bridge",
        x: 78,
        y: 36,
        label: "Pont des Arts",
        sublabel: "vue",
        highlighted: true,
        stopNumber: 3,
      },
    ],
    stops: [
      {
        id: "rooftop",
        number: 1,
        name: "Rooftop Terrasse",
        category: "View",
        description: "Golden-hour skyline · quiet corner table",
        duration: "35 min stay",
        image: VIEW_GRAD,
        visualStyle: "view",
      },
      {
        id: "wine",
        number: 2,
        name: "Le Verre du Marais",
        category: "Wine bar",
        description: "Natural wines · candlelight · under €18 glass",
        duration: "12 min walk",
        image: REST_GRAD,
        visualStyle: "restaurant",
      },
      {
        id: "bridge",
        number: 3,
        name: "Pont des Arts",
        category: "Walk",
        description: "Slow river stroll as the city turns amber",
        duration: "8 min walk",
        image: VIEW_GRAD,
        visualStyle: "view",
      },
    ],
  },

  "night-safety": {
    id: "night-safety",
    label: "Night Safety",
    emoji: "🌙",
    sceneId: "minuit",
    headerPill: "Paris · Été · Minuit",
    accentColor: "#f0b45a",
    glowColor: "rgba(240, 180, 90, 0.35)",
    mapMood: "custom",
    title: "Night Safety Route",
    subtitle: "Well-lit streets and busy corners after dark",
    reply:
      "I kept you on bright, populated streets with late-open cafés nearby — no empty passages.",
    distance: "980 m",
    duration: "72 min",
    routePath: "M 88 218 C 120 205, 145 190, 175 182 S 235 165, 285 152 S 320 142, 345 135",
    markers: [
      {
        id: "lit-street",
        x: 28,
        y: 48,
        label: "Rue éclairée",
        sublabel: "passage sûr",
        highlighted: true,
        stopNumber: 1,
      },
      {
        id: "jazz",
        x: 52,
        y: 44,
        label: "Cellar jazz",
        sublabel: "last set",
        highlighted: true,
        stopNumber: 2,
      },
      {
        id: "metro",
        x: 72,
        y: 40,
        label: "Métro",
        sublabel: "sortie éclairée",
        highlighted: true,
        stopNumber: 3,
      },
    ],
    stops: [
      {
        id: "lit-street",
        number: 1,
        name: "Rue des Rosiers",
        category: "Safe corridor",
        description: "Continuous street lighting · active storefronts",
        duration: "15 min walk",
        image: SHOP_GRAD,
        visualStyle: "shop",
      },
      {
        id: "jazz",
        number: 2,
        name: "Cave Jazz du Marais",
        category: "Venue",
        description: "Busy cellar bar · staff at door · open late",
        duration: "40 min stay",
        image: REST_GRAD,
        visualStyle: "restaurant",
      },
      {
        id: "metro",
        number: 3,
        name: "Saint-Paul Metro",
        category: "Transit",
        description: "Lit exit · taxi rank · night bus nearby",
        duration: "6 min walk",
        image: SHOP_GRAD,
        visualStyle: "shop",
      },
    ],
  },

  "asthma-air-quality": {
    id: "asthma-air-quality",
    label: "Clean Air Path",
    emoji: "🌿",
    sceneId: "soft-day",
    headerPill: "Paris · Été · Air calme",
    accentColor: "#6b9a76",
    glowColor: "rgba(107, 154, 118, 0.4)",
    mapMood: "custom",
    title: "Clean Air Walk",
    subtitle: "Low pollution corridor for easier breathing",
    reply:
      "I routed you through parks and side streets with cleaner air — away from heavy traffic pockets.",
    distance: "1.4 km",
    duration: "88 min",
    routePath: "M 65 215 Q 100 200 130 190 T 200 175 T 280 160 T 350 148",
    markers: [
      {
        id: "park",
        x: 30,
        y: 42,
        label: "Square",
        sublabel: "air calme",
        highlighted: true,
        stopNumber: 1,
      },
      {
        id: "quiet-st",
        x: 55,
        y: 50,
        label: "Ruelle",
        sublabel: "peu de trafic",
        highlighted: true,
        stopNumber: 2,
      },
      {
        id: "cafe",
        x: 75,
        y: 44,
        label: "Terrasse",
        sublabel: "respire",
        highlighted: true,
        stopNumber: 3,
      },
    ],
    stops: [
      {
        id: "park",
        number: 1,
        name: "Square du Temple",
        category: "Park",
        description: "Tree canopy · lowest AQ readings on the loop",
        duration: "25 min stay",
        image: PARK_GRAD,
        visualStyle: "park",
      },
      {
        id: "quiet-st",
        number: 2,
        name: "Passage des Archives",
        category: "Quiet street",
        description: "Pedestrian-priority · minimal exhaust exposure",
        duration: "10 min walk",
        image: PARK_GRAD,
        visualStyle: "park",
      },
      {
        id: "cafe",
        number: 3,
        name: "Café des Jardins",
        category: "Café",
        description: "Outdoor seating set back from the boulevard",
        duration: "8 min walk",
        image: CAFE_GRAD,
        visualStyle: "cafe",
      },
    ],
  },

  "accessible-dining": {
    id: "accessible-dining",
    label: "Accessible Dining",
    emoji: "♿",
    sceneId: "soft-day",
    headerPill: "Paris · Été · Accès facile",
    accentColor: "#5b8def",
    glowColor: "rgba(91, 141, 239, 0.35)",
    mapMood: "custom",
    title: "Accessible Dining",
    subtitle: "Step-free terrasses and flat routes",
    reply:
      "Every stop has step-free access and wide seating — the path avoids stairs and cobble pinch points.",
    distance: "860 m",
    duration: "80 min",
    routePath: "M 90 212 L 140 198 L 185 188 L 235 178 L 290 168 L 340 158",
    markers: [
      {
        id: "ramp",
        x: 26,
        y: 46,
        label: "Terrasse",
        sublabel: "accès PMR",
        highlighted: true,
        stopNumber: 1,
      },
      {
        id: "bistro",
        x: 50,
        y: 48,
        label: "Bistro",
        sublabel: "sans marche",
        highlighted: true,
        stopNumber: 2,
      },
      {
        id: "dessert",
        x: 74,
        y: 42,
        label: "Salon de thé",
        sublabel: "large portes",
        highlighted: true,
        stopNumber: 3,
      },
    ],
    stops: [
      {
        id: "ramp",
        number: 1,
        name: "Terrasse Saint-Paul",
        category: "Restaurant",
        description: "Level entry · accessible restroom · terrace seating",
        duration: "40 min stay",
        image: REST_GRAD,
        visualStyle: "restaurant",
      },
      {
        id: "bistro",
        number: 2,
        name: "Bistro du Marais",
        category: "Bistro",
        description: "Step-free dining room · wide aisle spacing",
        duration: "6 min walk",
        image: REST_GRAD,
        visualStyle: "restaurant",
      },
      {
        id: "dessert",
        number: 3,
        name: "Salon Angelina",
        category: "Tea room",
        description: "Automatic door · ground-floor only",
        duration: "5 min walk",
        image: CAFE_GRAD,
        visualStyle: "cafe",
      },
    ],
  },

  "vi-transit": {
    id: "vi-transit",
    label: "VI Transit Plan",
    emoji: "🚇",
    sceneId: "soft-day",
    headerPill: "Paris · Été · Transit clair",
    accentColor: "#4a6fa5",
    glowColor: "rgba(74, 111, 165, 0.38)",
    mapMood: "culture",
    title: "Transit Clarity",
    subtitle: "Simple geometry · clear announcements",
    reply:
      "Short walks, straight transfers, and stations with tactile guidance — minimal line changes.",
    distance: "1.2 km",
    duration: "65 min",
    routePath: "M 85 215 L 155 200 L 155 175 L 225 175 L 225 155 L 310 155",
    markers: [
      {
        id: "metro-a",
        x: 38,
        y: 50,
        label: "Métro",
        sublabel: "annonces claires",
        highlighted: true,
        stopNumber: 1,
      },
      {
        id: "transfer",
        x: 58,
        y: 38,
        label: "Correspondance",
        sublabel: "tactile",
        highlighted: true,
        stopNumber: 2,
      },
      {
        id: "exit",
        x: 78,
        y: 34,
        label: "Sortie",
        sublabel: "guidage",
        highlighted: true,
        stopNumber: 3,
      },
    ],
    stops: [
      {
        id: "metro-a",
        number: 1,
        name: "Saint-Paul · Line 1",
        category: "Metro",
        description: "Audio announcements · consistent platform layout",
        duration: "12 min ride",
        image: SHOP_GRAD,
        visualStyle: "shop",
      },
      {
        id: "transfer",
        number: 2,
        name: "Hôtel de Ville",
        category: "Transfer",
        description: "Tactile strips · single-level connection",
        duration: "4 min transfer",
        image: GALLERY_GRAD,
        visualStyle: "gallery",
      },
      {
        id: "exit",
        number: 3,
        name: "Rivoli · Exit 3",
        category: "Exit",
        description: "Wide exit · straight street crossing",
        duration: "3 min walk",
        image: VIEW_GRAD,
        visualStyle: "view",
      },
    ],
  },

  "sensory-friendly": {
    id: "sensory-friendly",
    label: "Sensory-Safe Outing",
    emoji: "🤫",
    sceneId: "soft-day",
    headerPill: "Paris · Été · Douceur",
    accentColor: "#a894c9",
    glowColor: "rgba(168, 148, 201, 0.38)",
    mapMood: "cozy",
    title: "Sensory-Safe Loop",
    subtitle: "Quiet corners · soft light · gentle pace",
    reply:
      "I avoided crowded boulevards and loud terraces — calm interiors and low-stimulus paths only.",
    distance: "740 m",
    duration: "90 min",
    routePath: "M 78 208 Q 115 198 150 192 Q 185 186 220 180 Q 260 172 300 165 Q 330 160 355 155",
    markers: [
      {
        id: "quiet-cafe",
        x: 32,
        y: 44,
        label: "Coin calme",
        sublabel: "peu de bruit",
        highlighted: true,
        stopNumber: 1,
      },
      {
        id: "garden",
        x: 54,
        y: 48,
        label: "Jardin",
        sublabel: "silence",
        highlighted: true,
        stopNumber: 2,
      },
      {
        id: "bookshop",
        x: 76,
        y: 42,
        label: "Librairie",
        sublabel: "feutré",
        highlighted: true,
        stopNumber: 3,
      },
    ],
    stops: [
      {
        id: "quiet-cafe",
        number: 1,
        name: "Café des Musées",
        category: "Café",
        description: "Back room seating · no music after 18h",
        duration: "35 min stay",
        image: CAFE_GRAD,
        visualStyle: "cafe",
      },
      {
        id: "garden",
        number: 2,
        name: "Jardin Saint-Gilles",
        category: "Garden",
        description: "Low foot traffic · shaded bench loop",
        duration: "10 min walk",
        image: PARK_GRAD,
        visualStyle: "park",
      },
      {
        id: "bookshop",
        number: 3,
        name: "Librairie du Temple",
        category: "Bookshop",
        description: "Quiet floors · soft lighting · no flashing displays",
        duration: "7 min walk",
        image: GALLERY_GRAD,
        visualStyle: "gallery",
      },
    ],
  },
};

export const DEMO_SCENARIO_LIST = Object.values(DEMO_BUNDLES);

export const DEMO_CHIP_OPTIONS = DEMO_SCENARIO_LIST.map((bundle) => ({
  id: bundle.id,
  label: bundle.label,
  emoji: bundle.emoji,
  accentColor: bundle.accentColor,
}));

export function buildIntentFromDemoBundle(bundle: DemoBundle): LivingParisIntent {
  return {
    id: bundle.id,
    label: bundle.label,
    icon: <IntentIcon mood={bundle.mapMood} emoji={bundle.emoji} />,
    accentColor: bundle.accentColor,
    glowColor: bundle.glowColor,
    mapMood: bundle.mapMood,
    title: bundle.title,
    subtitle: bundle.subtitle,
    response: bundle.reply,
    distance: bundle.distance,
    duration: bundle.duration,
    route: [],
    stops: bundle.stops,
  };
}
